# Generated by Django 5.2 on 2026-03-10 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aplicacao",
            fields=[
                ("idaplicacao", models.AutoField(primary_key=True, serialize=False)),
                ("codigointerno", models.CharField(max_length=50, unique=True)),
                ("nomeaplicacao", models.CharField(max_length=200)),
                ("base_url", models.URLField(blank=True, null=True)),
                ("isshowinportal", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Aplicação",
                "verbose_name_plural": "Aplicações",
                "db_table": "tblaplicacao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ClassificacaoUsuario",
            fields=[
                (
                    "idclassificacaousuario",
                    models.SmallIntegerField(
                        db_column="idclassificacaousuario",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "strdescricao",
                    models.CharField(db_column="strdescricao", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Classificação de Usuário",
                "verbose_name_plural": "Classificações de Usuários",
                "db_table": "tblclassificacaousuario",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StatusUsuario",
            fields=[
                (
                    "idstatususuario",
                    models.SmallIntegerField(
                        db_column="idstatususuario", primary_key=True, serialize=False
                    ),
                ),
                (
                    "strdescricao",
                    models.CharField(db_column="strdescricao", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Status de Usuário",
                "verbose_name_plural": "Status de Usuários",
                "db_table": "tblstatususuario",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TipoUsuario",
            fields=[
                (
                    "idtipousuario",
                    models.SmallIntegerField(
                        db_column="idtipousuario", primary_key=True, serialize=False
                    ),
                ),
                (
                    "strdescricao",
                    models.CharField(db_column="strdescricao", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Tipo de Usuário",
                "verbose_name_plural": "Tipos de Usuários",
                "db_table": "tbltipousuario",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeperfil", models.CharField(max_length=100)),
                ("codigoperfil", models.CharField(max_length=100)),
                (
                    "aplicacao",
                    models.ForeignKey(
                        db_column="aplicacao_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.aplicacao",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Grupo Django correspondente. Criado automaticamente via signal se não informado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "accounts_role",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, db_column="strnome", max_length=200),
                ),
                (
                    "orgao",
                    models.CharField(
                        blank=True, db_column="orgao", max_length=100, null=True
                    ),
                ),
                (
                    "datacriacao",
                    models.DateTimeField(auto_now_add=True, db_column="datacriacao"),
                ),
                (
                    "data_alteracao",
                    models.DateTimeField(
                        auto_now=True, db_column="data_alteracao", null=True
                    ),
                ),
                (
                    "classificacao_usuario",
                    models.ForeignKey(
                        db_column="idclassificacaousuario",
                        default=apps.accounts.models.get_default_classificacao_usuario,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.classificacaousuario",
                    ),
                ),
                (
                    "idusuarioalteracao",
                    models.ForeignKey(
                        blank=True,
                        db_column="idusuarioalteracao",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles_alterados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idusuariocriacao",
                    models.ForeignKey(
                        blank=True,
                        db_column="idusuariocriacao",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status_usuario",
                    models.ForeignKey(
                        db_column="idstatususuario",
                        default=apps.accounts.models.get_default_status_usuario,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.statususuario",
                    ),
                ),
                (
                    "tipo_usuario",
                    models.ForeignKey(
                        db_column="idtipousuario",
                        default=apps.accounts.models.get_default_tipo_usuario,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.tipousuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "tblusuario",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aplicacao",
                    models.ForeignKey(
                        db_column="aplicacao_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.aplicacao",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "accounts_userrole",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AccountsSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked", models.BooleanField(db_index=True, default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "db_table": "accounts_session",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["jti", "revoked"], name="accounts_se_jti_6a3eb0_idx"
                    ),
                    models.Index(
                        fields=["user", "revoked"],
                        name="accounts_se_user_id_1162b2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=255)),
                (
                    "aplicacao",
                    models.ForeignKey(
                        db_column="aplicacao_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.aplicacao",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
                "db_table": "accounts_attribute",
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "aplicacao", "key"),
                        name="uq_attribute_user_aplicacao_key",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("aplicacao", "codigoperfil"),
                name="uq_role_aplicacao_codigoperfil",
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("user", "aplicacao", "role"),
                name="uq_userrole_user_aplicacao_role",
            ),
        ),
    ]
