# Generated by Django 5.2 on 2026-03-31 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_refactor_accountssession_jwt_to_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountssession',
            name='session_cookie_name',
            field=models.CharField(blank=True, default='\\', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='accountssession',
            index=models.Index(fields=['session_cookie_name'], name='accounts_se_session_5069be_idx'),
        ),
    ]
