# Generated by Django 5.2 on 2026-04-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_userauthzstate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userpermissionoverride',
            new_name='accounts_us_user_id_32f3bf_idx',
            old_name='accounts_us_user_id_mode_idx',
        ),
        migrations.RenameIndex(
            model_name='userpermissionoverride',
            new_name='accounts_us_permiss_1b6a26_idx',
            old_name='accounts_us_perm_id_idx',
        ),
    ]
