# Generated by Django 5.2 on 2026-10-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0012_rename_accounts_us_user_id_mode_idx_accounts_us_user_id_32f3bf_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código interno único da capability dentro da aplicação.",
                        max_length=100,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome funcional apresentado na administração.",
                        max_length=200,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descrição do recurso funcional.",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se a capability está disponível para distribuição.",
                    ),
                ),
                (
                    "aplicacao",
                    models.ForeignKey(
                        db_column="aplicacao_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="accounts.aplicacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capability",
                "verbose_name_plural": "Capabilities",
                "db_table": "accounts_capability",
                "ordering": ["aplicacao", "codigo"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código interno único do item de menu na aplicação.",
                        max_length=100,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Texto apresentado no menu.", max_length=200
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descrição opcional do item de menu.",
                    ),
                ),
                (
                    "rota",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Rota da aplicação. Pode ficar vazia para menus agrupadores.",
                        max_length=255,
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identificador do ícone utilizado pelo frontend.",
                        max_length=100,
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de apresentação dentro do nível do menu.",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o item está disponível na navegação.",
                    ),
                ),
                (
                    "aplicacao",
                    models.ForeignKey(
                        db_column="aplicacao_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="accounts.aplicacao",
                    ),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        blank=True,
                        help_text="Capability funcional representada pelo item."
                        + " Opcional para menus agrupadores ou itens sem capability própria.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menus",
                        to="accounts.capability",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Menu pai. Vazio quando o item estiver no nível raiz.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounts.menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "db_table": "accounts_menu",
                "ordering": ["aplicacao", "parent", "ordem", "codigo"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RoleCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aplicacao",
                    models.ForeignKey(
                        db_column="aplicacao_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_capabilities",
                        to="accounts.aplicacao",
                    ),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_capabilities",
                        to="accounts.capability",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_capabilities",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Capability",
                "verbose_name_plural": "Role Capabilities",
                "db_table": "accounts_rolecapability",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="capability",
            index=models.Index(
                fields=["aplicacao", "ativo"], name="accounts_ca_aplicac_515130_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="capability",
            constraint=models.UniqueConstraint(
                fields=("aplicacao", "codigo"), name="uq_capability_aplicacao_codigo"
            ),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["aplicacao", "ativo"], name="accounts_me_aplicac_0f5976_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["aplicacao", "parent", "ordem"],
                name="accounts_me_aplicac_2bed71_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                fields=("aplicacao", "codigo"), name="uq_menu_aplicacao_codigo"
            ),
        ),
        migrations.AddIndex(
            model_name="rolecapability",
            index=models.Index(
                fields=["aplicacao", "role"], name="accounts_ro_aplicac_333839_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolecapability",
            index=models.Index(
                fields=["aplicacao", "capability"],
                name="accounts_ro_aplicac_b5b2f3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolecapability",
            constraint=models.UniqueConstraint(
                fields=("aplicacao", "role", "capability"),
                name="uq_rolecapability_aplicacao_role_capability",
            ),
        ),
    ]
