# Generated by Django 5.2 on 2026-10-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_capability_menu_rolecapability_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={
                "managed": True,
                "ordering": ["aplicacao", "parent_id", "ordem", "codigo"],
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
            },
        ),
    ]
