# Generated by Django 5.2 on 2026-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carga_org_lot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detalhestatuscarga",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="detalhestatuscarga",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="patriarca",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="patriarca",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="tokenenviocarga",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="tokenenviocarga",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="detalhestatuscarga",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="detalhestatuscarga",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="detalhestatuscarga",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="detalhestatuscarga",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="patriarca",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patriarca",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="patriarca",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patriarca",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tokenenviocarga",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tokenenviocarga",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tokenenviocarga",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tokenenviocarga",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="detalhestatuscarga",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="detalhestatuscarga",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AlterField(
            model_name="patriarca",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="patriarca",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AlterField(
            model_name="tokenenviocarga",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="tokenenviocarga",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
    ]
