# Generated by Django 5.2 on 2026-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acoes_pngi", "0003_fix_remove_fk_usuarioresponsavel_authuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acaoanotacaoalinhamento",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="acaoanotacaoalinhamento",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="acaodestaque",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="acaodestaque",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="acaoprazo",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="acaoprazo",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="acoes",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="acoes",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="eixo",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="eixo",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="vigenciapngi",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="vigenciapngi",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="acaoanotacaoalinhamento",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="acaoanotacaoalinhamento",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="acaoanotacaoalinhamento",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="acaoanotacaoalinhamento",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="acaodestaque",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="acaodestaque",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="acaodestaque",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="acaodestaque",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="acaoprazo",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="acaoprazo",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="acaoprazo",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="acaoprazo",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="acoes",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="acoes",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="acoes",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="acoes",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="eixo",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eixo",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="eixo",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eixo",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="vigenciapngi",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vigenciapngi",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="vigenciapngi",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vigenciapngi",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="acaoanotacaoalinhamento",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="acaoanotacaoalinhamento",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AlterField(
            model_name="acaodestaque",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="acaodestaque",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AlterField(
            model_name="acaoprazo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="acaoprazo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AlterField(
            model_name="acoes",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="acoes",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AlterField(
            model_name="eixo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="eixo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AlterField(
            model_name="vigenciapngi",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="vigenciapngi",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
    ]
