# Generated by Django 5.2 on 2026-03-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acoes_pngi", "0004_refactor_auditablemodel_remove_fk_auth_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="acoes",
            name="ideixo",
            field=models.ForeignKey(
                blank=True,
                db_column="ideixo",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acoes",
                to="acoes_pngi.eixo",
            ),
        ),
        migrations.AddField(
            model_name="acoes",
            name="idsituacaoacao",
            field=models.ForeignKey(
                blank=True,
                db_column="idsituacaoacao",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acoes",
                to="acoes_pngi.situacaoacao",
            ),
        ),
    ]
