# Generated by Django 5.2 on 2026-04-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes_pngi', '0005_acoes_ideixo_acoes_idsituacaoacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acaoanotacaoalinhamento',
            options={'ordering': ['idacaoanotacaoalinhamento']},
        ),
        migrations.AlterModelOptions(
            name='acaodestaque',
            options={'ordering': ['-datdatadestaque']},
        ),
        migrations.AlterModelOptions(
            name='acaoprazo',
            options={'ordering': ['idacaoprazo']},
        ),
        migrations.AlterModelOptions(
            name='tipoanotacaoalinhamento',
            options={'ordering': ['strdescricaotipoanotacaoalinhamento']},
        ),
        migrations.AlterModelOptions(
            name='tipoentravealerta',
            options={'ordering': ['strdescricaotipoentravealerta']},
        ),
    ]
