# Generated by Django 5.2 on 2026-10-05 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acoes_pngi", "0006_alter_acaoanotacaoalinhamento_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relacaoacaousuarioresponsavel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relacaoacaousuarioresponsavel",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="relacaoacaousuarioresponsavel",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="relacaoacaousuarioresponsavel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AddField(
            model_name="relacaoacaousuarioresponsavel",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="relacaoacaousuarioresponsavel",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="situacaoacao",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="situacaoacao",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="situacaoacao",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="situacaoacao",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AddField(
            model_name="situacaoacao",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="situacaoacao",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tipoanotacaoalinhamento",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tipoanotacaoalinhamento",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tipoanotacaoalinhamento",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tipoanotacaoalinhamento",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AddField(
            model_name="tipoanotacaoalinhamento",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tipoanotacaoalinhamento",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tipoentravealerta",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tipoentravealerta",
            name="created_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="created_by_id",
                editable=False,
                help_text="ID lógico do usuário que criou o registro (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tipoentravealerta",
            name="created_by_name",
            field=models.CharField(
                blank=True,
                db_column="created_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da criação — imutável.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tipoentravealerta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AddField(
            model_name="tipoentravealerta",
            name="updated_by_id",
            field=models.IntegerField(
                blank=True,
                db_column="updated_by_id",
                editable=False,
                help_text="ID lógico do usuário que fez a última alteração (sem FK para auth_user).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tipoentravealerta",
            name="updated_by_name",
            field=models.CharField(
                blank=True,
                db_column="updated_by_name",
                default="",
                editable=False,
                help_text="Snapshot do username no momento da última alteração — imutável.",
                max_length=200,
            ),
        ),
    ]
